In [38]:
import pandas as pd
import numpy as np
import tensorflow as tf

print(tf.__version__)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

print("ANN imports successful")
import seaborn as sns
import matplotlib.pyplot as plt

2.21.0
ANN imports successful

In [39]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\Hp\AppData\Local\Programs\Python\Python313\python.exe
3.13.14 (tags/v3.13.14:fd17997, Jun 10 2026, 13:03:48) [MSC v.1944 64 bit (AMD64)]

In [40]:
df= pd.read_csv('car_price_prediction_dataset.csv')
df.head()

,Car_ID,Brand,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Price
0,1,Mercedes,2012,148273,Electric,Manual,Third,1816,8.7,5,162000
1,2,Hyundai,2019,34426,Diesel,Manual,First,2727,27.1,5,1341000
2,3,Tata,2023,22778,Petrol,Manual,First,2353,12.2,5,906000
3,4,BMW,2022,47229,Diesel,Manual,Second,856,23.8,7,1384000
4,5,Mercedes,2023,91652,Petrol,Manual,First,2959,23.5,4,1677000

In [41]:
df.drop('Car_ID',axis=1,inplace=True)

In [42]:
df.isnull().sum()

Brand                0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner                0
Engine_CC            0
Mileage_kmpl         0
Seats                0
Price                0
dtype: int64

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              1000 non-null   str
 1   Year               1000 non-null   int64
 2   Kilometers_Driven  1000 non-null   int64
 3   Fuel_Type          1000 non-null   str
 4   Transmission       1000 non-null   str
 5   Owner              1000 non-null   str
 6   Engine_CC          1000 non-null   int64
 7   Mileage_kmpl       1000 non-null   float64
 8   Seats              1000 non-null   int64
 9   Price              1000 non-null   int64
dtypes: float64(1), int64(5), str(4)
memory usage: 78.3 KB

In [45]:
df.describe()

,Year,Kilometers_Driven,Engine_CC,Mileage_kmpl,Seats,Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2018.504000,93376.190000,2668.994000,17.895600,5.205000,9.745840e+05
std,4.080764,50912.537009,1094.029959,5.829376,0.819541,4.714313e+05
min,2012.000000,5163.000000,804.000000,8.000000,4.000000,1.200000e+05
25%,2015.000000,47457.000000,1734.000000,12.700000,5.000000,6.367500e+05
50%,2019.000000,94476.500000,2705.500000,18.000000,5.000000,9.835000e+05
75%,2022.000000,138824.500000,3596.250000,22.700000,5.000000,1.318000e+06
max,2025.000000,179668.000000,4499.000000,28.000000,7.000000,2.312000e+06

In [85]:
df.Brand.unique()
df.loc[(df.Brand=='BMW') & (df.Year==2025)]

,Brand,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Price
20,BMW,2025,171205,CNG,Automatic,Second,3745,17.9,5,1622000
127,BMW,2025,167962,Diesel,Manual,First,2004,12.3,5,969000
290,BMW,2025,129457,Petrol,Automatic,First,3839,9.6,5,1702000
482,BMW,2025,81373,Petrol,Manual,First,3377,22.9,5,2052000
494,BMW,2025,158812,Petrol,Automatic,First,2225,21.0,5,1547000
523,BMW,2025,166983,Diesel,Manual,First,4150,9.9,5,1354000
696,BMW,2025,24873,CNG,Manual,Third,3585,20.3,5,1862000
754,BMW,2025,62775,Diesel,Manual,First,3028,17.9,7,1596000
941,BMW,2025,86816,Petrol,Manual,Second,1896,21.3,5,1669000

In [47]:
df.Fuel_Type.unique()

<StringArray>
['Electric', 'Diesel', 'Petrol', 'CNG']
Length: 4, dtype: str

In [48]:
df.Transmission.unique()

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [49]:
df.select_dtypes(include='O').columns

C:\Users\Hp\AppData\Local\Temp\ipykernel_4776\1932503071.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='O').columns

Index(['Brand', 'Fuel_Type', 'Transmission', 'Owner'], dtype='str')

In [50]:
df.Owner.unique()

<StringArray>
['Third', 'First', 'Second']
Length: 3, dtype: str

In [51]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder,StandardScaler
from sklearn.model_selection import train_test_split
X = df.drop('Price',axis=1)
y = df['Price']

In [ ]:
X.head()

AttributeError: 'DataFrame' object has no attribute 'Brand'

In [53]:
y.head()

0     162000
1    1341000
2     906000
3    1384000
4    1677000
Name: Price, dtype: int64

In [54]:
oe = OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore')
brand_Fuel_encoded = oe.fit_transform(df[['Brand','Fuel_Type']])
brand_Fuel_encoded_df = pd.DataFrame(brand_Fuel_encoded,columns=oe.get_feature_names_out(['Brand','Fuel_Type']))
brand_Fuel_encoded_df.head()

,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [55]:
X=pd.concat([X.drop(['Brand','Fuel_Type'],axis=1),brand_Fuel_encoded_df],axis=1)
X.head()

,Year,Kilometers_Driven,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,2012,148273,Manual,Third,1816,8.7,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,2019,34426,Manual,First,2727,27.1,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2023,22778,Manual,First,2353,12.2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,2022,47229,Manual,Second,856,23.8,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2023,91652,Manual,First,2959,23.5,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [56]:
X.Year = 2026-X.Year
X.head()

,Year,Kilometers_Driven,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,14,148273,Manual,Third,1816,8.7,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,7,34426,Manual,First,2727,27.1,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,22778,Manual,First,2353,12.2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,47229,Manual,Second,856,23.8,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,3,91652,Manual,First,2959,23.5,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [57]:
label_encoder = LabelEncoder()
X['Transmission'] = label_encoder.fit_transform(X['Transmission'])
X.head()

,Year,Kilometers_Driven,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,14,148273,1,Third,1816,8.7,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,7,34426,1,First,2727,27.1,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,22778,1,First,2353,12.2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,47229,1,Second,856,23.8,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,3,91652,1,First,2959,23.5,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [58]:
ordinal = OrdinalEncoder(categories=[['First','Second','Third']])
X[['Owner']] = ordinal.fit_transform(X[['Owner']])
X.head()

,Year,Kilometers_Driven,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,14,148273,1,2.0,1816,8.7,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,7,34426,1,0.0,2727,27.1,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,22778,1,0.0,2353,12.2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,47229,1,1.0,856,23.8,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,3,91652,1,0.0,2959,23.5,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [59]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=33)

In [60]:
stdSc = StandardScaler()
X_train_scaled = stdSc.fit_transform(X_train)
X_test_scaled = stdSc.transform(X_test)

In [64]:
np.array(X_train_scaled).shape

(700, 19)

In [65]:
X_train_scaled.shape

(700, 19)

In [67]:
X_test_scaled.shape
import pickle

In [69]:
with open('models/one_hot_encoder.pkl','wb') as file:
    pickle.dump(oe,file)
with open('models/label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)
with open('models/ordinal_encoder.pkl','wb') as file:
    pickle.dump(ordinal,file)
with open('models/StandardScaler.pkl','wb') as file:
    pickle.dump(stdSc,file)

In [70]:
X.head()

,Year,Kilometers_Driven,Transmission,Owner,Engine_CC,Mileage_kmpl,Seats,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Hyundai,Brand_Kia,Brand_Maruti,Brand_Mercedes,Brand_Tata,Brand_Toyota,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol
0,14,148273,1,2.0,1816,8.7,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,7,34426,1,0.0,2727,27.1,5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,22778,1,0.0,2353,12.2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,47229,1,1.0,856,23.8,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,3,91652,1,0.0,2959,23.5,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [78]:
model = Sequential()
model.add(Dense(256,activation='relu',input_shape=(X_train_scaled.shape[1],)))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1))

model.compile(optimizer='adam',loss='mse',metrics=['mae'])
model.summary()

c:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 256)            │         5,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 48,385 (189.00 KB)

 Trainable params: 48,385 (189.00 KB)

 Non-trainable params: 0 (0.00 B)

In [79]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping_calback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [80]:
history = model.fit(
    X_train_scaled,
    y_train,
    validation_split=0.3,
    epochs=200,
    batch_size = 32,
    callbacks=[early_stopping_calback]
)


from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test_scaled).flatten()

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

Epoch 1/200

16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 1186508570624.0000 - mae: 983239.8125 - val_loss: 1147516485632.0000 - val_mae: 959790.5000
Epoch 2/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1186481438720.0000 - mae: 983226.1875 - val_loss: 1147459338240.0000 - val_mae: 959761.3750
Epoch 3/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1186358493184.0000 - mae: 983167.1250 - val_loss: 1147231797248.0000 - val_mae: 959648.3750
Epoch 4/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1185925562368.0000 - mae: 982960.3750 - val_loss: 1146483638272.0000 - val_mae: 959286.3750
Epoch 5/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1184611434496.0000 - mae: 982347.6250 - val_loss: 1144397234176.0000 - val_mae: 958296.1875
Epoch 6/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1181128458240.0000 - mae: 980765.8125 - val_loss: 1139412434944.0000 - val_mae: 955962.8125
Epoch 7/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1173544632320.0000 - mae: 977261.8750 - val_loss: 1128729935872.0000 - val_mae: 951023.8750
Epoch 8/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1157859246080.0000 - mae: 970155.0625 - val_loss: 1108106280960.0000 - val_mae: 941523.0625
Epoch 9/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1128514846720.0000 - mae: 956927.4375 - val_loss: 1071524216832.0000 - val_mae: 924628.5000
Epoch 10/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1078552756224.0000 - mae: 933935.2500 - val_loss: 1010766512128.0000 - val_mae: 896145.7500
Epoch 11/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 999308918784.0000 - mae: 896567.8125 - val_loss: 918616670208.0000 - val_mae: 851380.0000
Epoch 12/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 881267638272.0000 - mae: 839157.2500 - val_loss: 790642294784.0000 - val_mae: 785480.2500
Epoch 13/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 724340768768.0000 - mae: 755543.0000 - val_loss: 625756667904.0000 - val_mae: 693159.9375
Epoch 14/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 532890779648.0000 - mae: 640767.7500 - val_loss: 437175648256.0000 - val_mae: 570979.0625
Epoch 15/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 333987053568.0000 - mae: 498215.4688 - val_loss: 263776550912.0000 - val_mae: 432276.0625
Epoch 16/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 175472197632.0000 - mae: 348427.2812 - val_loss: 138847305728.0000 - val_mae: 307318.4375
Epoch 17/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 80910188544.0000 - mae: 229197.9844 - val_loss: 83400630272.0000 - val_mae: 233419.1719
Epoch 18/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 51234430976.0000 - mae: 181008.0000 - val_loss: 65046077440.0000 - val_mae: 201949.6562
Epoch 19/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 42695262208.0000 - mae: 165090.6250 - val_loss: 57274425344.0000 - val_mae: 187686.2969
Epoch 20/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 37734031360.0000 - mae: 155260.4688 - val_loss: 52083322880.0000 - val_mae: 179518.9062
Epoch 21/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 34628087808.0000 - mae: 149913.2812 - val_loss: 49261793280.0000 - val_mae: 175331.6406
Epoch 22/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32923176960.0000 - mae: 146119.8750 - val_loss: 47100915712.0000 - val_mae: 171620.5312
Epoch 23/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31652485120.0000 - mae: 143351.9219 - val_loss: 45770944512.0000 - val_mae: 168703.9219
Epoch 24/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 30744127488.0000 - mae: 141319.2812 - val_loss: 44604215296.0000 - val_mae: 166146.6406
Epoch 25/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 29986217984.0000 - mae: 139654.4219 - val_loss: 43708051456.0000 - val_mae: 164765.1406
Epoch 26/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 29327747072.0000 - mae: 138198.0000 - val_loss: 43325104128.0000 - val_mae: 163547.3438
Epoch 27/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 28854009856.0000 - mae: 136891.2812 - val_loss: 42617434112.0000 - val_mae: 161913.0469
Epoch 28/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 28380252160.0000 - mae: 135909.5312 - val_loss: 42213122048.0000 - val_mae: 161376.6562
Epoch 29/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28087099392.0000 - mae: 135323.3750 - val_loss: 41690480640.0000 - val_mae: 160325.1562
Epoch 30/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27742263296.0000 - mae: 134423.7500 - val_loss: 41688940544.0000 - val_mae: 159930.1094
Epoch 31/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27439675392.0000 - mae: 133568.4375 - val_loss: 41279242240.0000 - val_mae: 158826.5469
Epoch 32/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27208110080.0000 - mae: 133005.6875 - val_loss: 41004990464.0000 - val_mae: 158593.1875
Epoch 33/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26937503744.0000 - mae: 132197.3750 - val_loss: 40809050112.0000 - val_mae: 157871.7188
Epoch 34/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26673217536.0000 - mae: 131382.6250 - val_loss: 40553709568.0000 - val_mae: 157340.3594
Epoch 35/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26491394048.0000 - mae: 130824.4609 - val_loss: 40450285568.0000 - val_mae: 157179.0156
Epoch 36/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26322223104.0000 - mae: 130391.3125 - val_loss: 40576045056.0000 - val_mae: 157641.1875
Epoch 37/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26052489216.0000 - mae: 129676.6484 - val_loss: 40522915840.0000 - val_mae: 157091.2344
Epoch 38/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25955815424.0000 - mae: 129219.1016 - val_loss: 40390393856.0000 - val_mae: 156444.0625
Epoch 39/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25948850176.0000 - mae: 129565.9062 - val_loss: 40177446912.0000 - val_mae: 157405.7656
Epoch 40/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25494206464.0000 - mae: 128195.0000 - val_loss: 40194650112.0000 - val_mae: 156543.1250
Epoch 41/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25457408000.0000 - mae: 127911.0078 - val_loss: 40240119808.0000 - val_mae: 156432.3750
Epoch 42/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25220397056.0000 - mae: 127446.6641 - val_loss: 39857631232.0000 - val_mae: 155701.6719
Epoch 43/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25055176704.0000 - mae: 127078.8438 - val_loss: 39673950208.0000 - val_mae: 155624.6094
Epoch 44/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24919535616.0000 - mae: 126737.9844 - val_loss: 39608623104.0000 - val_mae: 155662.7656
Epoch 45/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24784267264.0000 - mae: 126311.9219 - val_loss: 39668019200.0000 - val_mae: 155635.3125
Epoch 46/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24603768832.0000 - mae: 125825.1250 - val_loss: 39469219840.0000 - val_mae: 155290.4531
Epoch 47/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24551677952.0000 - mae: 125774.6797 - val_loss: 39359426560.0000 - val_mae: 155171.9688
Epoch 48/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24367286272.0000 - mae: 125286.8594 - val_loss: 39366807552.0000 - val_mae: 154983.0312
Epoch 49/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24402507776.0000 - mae: 125251.8828 - val_loss: 39348191232.0000 - val_mae: 154794.4688
Epoch 50/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24128331776.0000 - mae: 124459.9062 - val_loss: 39388061696.0000 - val_mae: 155386.6094
Epoch 51/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24015691776.0000 - mae: 124294.0234 - val_loss: 39478820864.0000 - val_mae: 155435.0000
Epoch 52/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23862177792.0000 - mae: 123738.9531 - val_loss: 39480786944.0000 - val_mae: 155464.8906
Epoch 53/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23753416704.0000 - mae: 123536.4609 - val_loss: 39423455232.0000 - val_mae: 155523.6719
Epoch 54/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23688691712.0000 - mae: 123258.5781 - val_loss: 39469916160.0000 - val_mae: 155280.8906
Epoch 55/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23526062080.0000 - mae: 122947.5547 - val_loss: 39370424320.0000 - val_mae: 155247.4688
Epoch 56/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23422009344.0000 - mae: 122488.9141 - val_loss: 39238729728.0000 - val_mae: 154627.8438
Epoch 57/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23367206912.0000 - mae: 122515.6562 - val_loss: 39125463040.0000 - val_mae: 154573.8438
Epoch 58/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 23432802304.0000 - mae: 122608.2266 - val_loss: 39233654784.0000 - val_mae: 154605.1875
Epoch 59/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23155394560.0000 - mae: 121805.4219 - val_loss: 39069540352.0000 - val_mae: 154975.8281
Epoch 60/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23052617728.0000 - mae: 121707.3438 - val_loss: 39086546944.0000 - val_mae: 155042.5938
Epoch 61/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22966097920.0000 - mae: 121369.3750 - val_loss: 38996082688.0000 - val_mae: 155013.7656
Epoch 62/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22838941696.0000 - mae: 121010.1250 - val_loss: 38949416960.0000 - val_mae: 154731.2344
Epoch 63/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22795730944.0000 - mae: 120778.4062 - val_loss: 38951243776.0000 - val_mae: 154691.5625
Epoch 64/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22721142784.0000 - mae: 120300.3281 - val_loss: 39011696640.0000 - val_mae: 154644.2344
Epoch 65/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22626588672.0000 - mae: 120575.1641 - val_loss: 38900621312.0000 - val_mae: 154992.0625
Epoch 66/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22567753728.0000 - mae: 120361.1094 - val_loss: 38918643712.0000 - val_mae: 155015.0000
Epoch 67/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22406580224.0000 - mae: 119594.7031 - val_loss: 39046602752.0000 - val_mae: 154642.2500
Epoch 68/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22340214784.0000 - mae: 119807.4766 - val_loss: 38813499392.0000 - val_mae: 154747.1719
Epoch 69/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22237779968.0000 - mae: 119542.2969 - val_loss: 38746169344.0000 - val_mae: 154234.0781
Epoch 70/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22221576192.0000 - mae: 119140.6484 - val_loss: 38781800448.0000 - val_mae: 154276.0156
Epoch 71/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 22041702400.0000 - mae: 118657.3906 - val_loss: 38939459584.0000 - val_mae: 154522.0625
Epoch 72/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21959360512.0000 - mae: 118418.2812 - val_loss: 39017488384.0000 - val_mae: 154708.1719
Epoch 73/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21902381056.0000 - mae: 118368.9844 - val_loss: 39097155584.0000 - val_mae: 154846.6094
Epoch 74/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21862432768.0000 - mae: 118401.9844 - val_loss: 38972022784.0000 - val_mae: 154783.5781
Epoch 75/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21834502144.0000 - mae: 118458.1016 - val_loss: 38953521152.0000 - val_mae: 155027.5781
Epoch 76/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 21591750656.0000 - mae: 117618.7812 - val_loss: 39039713280.0000 - val_mae: 154861.7656
Epoch 77/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21654233088.0000 - mae: 117666.8594 - val_loss: 39129362432.0000 - val_mae: 155048.0156
Epoch 78/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21498253312.0000 - mae: 117602.5938 - val_loss: 38821330944.0000 - val_mae: 154518.9062
Epoch 79/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21505685504.0000 - mae: 117779.1328 - val_loss: 38969057280.0000 - val_mae: 154870.9375
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
MAE : 157897.734375
MSE : 38700437504.0
RMSE: 196724.26770482588
R2  : 0.8260083198547363

In [82]:
model.save('models/model.keras')